// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=SearchWord,proto3" json:"SearchWord,omitempty"`
	Pagination           int32    `protobuf:"varint,2,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_72214e036bf3a62b, []int{0}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (dst *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(dst, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *SearchRequest) GetPagination() int32 {
	if m != nil {
		return m.Pagination
	}
	return 0
}

type SearchResponse struct {
	Search               []*SearchDetail `protobuf:"bytes,1,rep,name=Search,proto3" json:"Search,omitempty"`
	TotalResponse        string          `protobuf:"bytes,2,opt,name=TotalResponse,proto3" json:"TotalResponse,omitempty"`
	Response             string          `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_72214e036bf3a62b, []int{1}
}
func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (dst *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(dst, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetSearch() []*SearchDetail {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *SearchResponse) GetTotalResponse() string {
	if m != nil {
		return m.TotalResponse
	}
	return ""
}

func (m *SearchResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type SearchDetail struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Year                 string   `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	ImdbID               string   `protobuf:"bytes,3,opt,name=imdbID,proto3" json:"imdbID,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Poster               string   `protobuf:"bytes,5,opt,name=Poster,proto3" json:"Poster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchDetail) Reset()         { *m = SearchDetail{} }
func (m *SearchDetail) String() string { return proto.CompactTextString(m) }
func (*SearchDetail) ProtoMessage()    {}
func (*SearchDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_72214e036bf3a62b, []int{2}
}
func (m *SearchDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchDetail.Unmarshal(m, b)
}
func (m *SearchDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchDetail.Marshal(b, m, deterministic)
}
func (dst *SearchDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchDetail.Merge(dst, src)
}
func (m *SearchDetail) XXX_Size() int {
	return xxx_messageInfo_SearchDetail.Size(m)
}
func (m *SearchDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchDetail.DiscardUnknown(m)
}

var xxx_messageInfo_SearchDetail proto.InternalMessageInfo

func (m *SearchDetail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchDetail) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *SearchDetail) GetImdbID() string {
	if m != nil {
		return m.ImdbID
	}
	return ""
}

func (m *SearchDetail) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchDetail) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

type GetRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_72214e036bf3a62b, []int{3}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetResponse struct {
	Title                string    `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Year                 string    `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Rated                string    `protobuf:"bytes,3,opt,name=Rated,proto3" json:"Rated,omitempty"`
	Released             string    `protobuf:"bytes,4,opt,name=Released,proto3" json:"Released,omitempty"`
	Runtime              string    `protobuf:"bytes,5,opt,name=Runtime,proto3" json:"Runtime,omitempty"`
	Genre                string    `protobuf:"bytes,6,opt,name=Genre,proto3" json:"Genre,omitempty"`
	Director             string    `protobuf:"bytes,7,opt,name=Director,proto3" json:"Director,omitempty"`
	Writer               string    `protobuf:"bytes,8,opt,name=Writer,proto3" json:"Writer,omitempty"`
	Actors               string    `protobuf:"bytes,9,opt,name=Actors,proto3" json:"Actors,omitempty"`
	Plot                 string    `protobuf:"bytes,10,opt,name=Plot,proto3" json:"Plot,omitempty"`
	Language             string    `protobuf:"bytes,11,opt,name=Language,proto3" json:"Language,omitempty"`
	Country              string    `protobuf:"bytes,12,opt,name=Country,proto3" json:"Country,omitempty"`
	Awards               string    `protobuf:"bytes,13,opt,name=Awards,proto3" json:"Awards,omitempty"`
	Poster               string    `protobuf:"bytes,14,opt,name=Poster,proto3" json:"Poster,omitempty"`
	Ratings              []*Rating `protobuf:"bytes,15,rep,name=Ratings,proto3" json:"Ratings,omitempty"`
	Metascore            string    `protobuf:"bytes,16,opt,name=Metascore,proto3" json:"Metascore,omitempty"`
	ImdbRating           string    `protobuf:"bytes,17,opt,name=ImdbRating,proto3" json:"ImdbRating,omitempty"`
	ImdbVotes            string    `protobuf:"bytes,18,opt,name=ImdbVotes,proto3" json:"ImdbVotes,omitempty"`
	ImdbID               string    `protobuf:"bytes,19,opt,name=ImdbID,proto3" json:"ImdbID,omitempty"`
	Type                 string    `protobuf:"bytes,20,opt,name=Type,proto3" json:"Type,omitempty"`
	DVD                  string    `protobuf:"bytes,21,opt,name=DVD,proto3" json:"DVD,omitempty"`
	BoxOffice            string    `protobuf:"bytes,22,opt,name=BoxOffice,proto3" json:"BoxOffice,omitempty"`
	Production           string    `protobuf:"bytes,23,opt,name=Production,proto3" json:"Production,omitempty"`
	Website              string    `protobuf:"bytes,24,opt,name=Website,proto3" json:"Website,omitempty"`
	Response             string    `protobuf:"bytes,25,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_72214e036bf3a62b, []int{4}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetResponse) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *GetResponse) GetRated() string {
	if m != nil {
		return m.Rated
	}
	return ""
}

func (m *GetResponse) GetReleased() string {
	if m != nil {
		return m.Released
	}
	return ""
}

func (m *GetResponse) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *GetResponse) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *GetResponse) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *GetResponse) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *GetResponse) GetActors() string {
	if m != nil {
		return m.Actors
	}
	return ""
}

func (m *GetResponse) GetPlot() string {
	if m != nil {
		return m.Plot
	}
	return ""
}

func (m *GetResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *GetResponse) GetAwards() string {
	if m != nil {
		return m.Awards
	}
	return ""
}

func (m *GetResponse) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *GetResponse) GetRatings() []*Rating {
	if m != nil {
		return m.Ratings
	}
	return nil
}

func (m *GetResponse) GetMetascore() string {
	if m != nil {
		return m.Metascore
	}
	return ""
}

func (m *GetResponse) GetImdbRating() string {
	if m != nil {
		return m.ImdbRating
	}
	return ""
}

func (m *GetResponse) GetImdbVotes() string {
	if m != nil {
		return m.ImdbVotes
	}
	return ""
}

func (m *GetResponse) GetImdbID() string {
	if m != nil {
		return m.ImdbID
	}
	return ""
}

func (m *GetResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetResponse) GetDVD() string {
	if m != nil {
		return m.DVD
	}
	return ""
}

func (m *GetResponse) GetBoxOffice() string {
	if m != nil {
		return m.BoxOffice
	}
	return ""
}

func (m *GetResponse) GetProduction() string {
	if m != nil {
		return m.Production
	}
	return ""
}

func (m *GetResponse) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *GetResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type Rating struct {
	Source               string   `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_72214e036bf3a62b, []int{5}
}
func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (dst *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(dst, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Rating) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "proto.SearchResponse")
	proto.RegisterType((*SearchDetail)(nil), "proto.SearchDetail")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto.RegisterType((*Rating)(nil), "proto.Rating")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_72214e036bf3a62b) }

var fileDescriptor_data_72214e036bf3a62b = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x8b, 0xd3, 0x4c,
	0x14, 0xa5, 0xbb, 0x9b, 0x74, 0x7b, 0xbb, 0xed, 0xb7, 0xdf, 0x6c, 0xad, 0xa3, 0x2c, 0x52, 0x8a,
	0x60, 0x41, 0xd8, 0x07, 0x05, 0xdf, 0xd5, 0xc0, 0x12, 0x50, 0xb6, 0x64, 0x4b, 0x8b, 0x8f, 0xd3,
	0xe4, 0x6e, 0x0d, 0xa4, 0x99, 0x3a, 0x99, 0xa0, 0x0b, 0x82, 0xff, 0xc2, 0xdf, 0x2b, 0x77, 0xee,
	0xa4, 0x4d, 0x7d, 0xf2, 0x29, 0x73, 0x4e, 0xce, 0x9c, 0x39, 0xf7, 0x72, 0x2f, 0x40, 0xa6, 0xac,
	0xba, 0xd9, 0x19, 0x6d, 0xb5, 0x08, 0xdc, 0x67, 0x7a, 0x07, 0x83, 0x7b, 0x54, 0x26, 0xfd, 0x9a,
	0xe0, 0xb7, 0x1a, 0x2b, 0x2b, 0x5e, 0x00, 0x30, 0xb1, 0xd2, 0x26, 0x93, 0x9d, 0x49, 0x67, 0xd6,
	0x4b, 0x5a, 0x0c, 0xfd, 0x9f, 0xab, 0x4d, 0x5e, 0x2a, 0x9b, 0xeb, 0x52, 0x9e, 0x4c, 0x3a, 0xb3,
	0x20, 0x69, 0x31, 0xd3, 0x5f, 0x30, 0x6c, 0x0c, 0xab, 0x9d, 0x2e, 0x2b, 0x14, 0xaf, 0x21, 0x64,
	0x46, 0x76, 0x26, 0xa7, 0xb3, 0xfe, 0x9b, 0x2b, 0x4e, 0x70, 0xc3, 0x64, 0x84, 0x56, 0xe5, 0x45,
	0xe2, 0x25, 0xe2, 0x25, 0x0c, 0x16, 0xda, 0xaa, 0xa2, 0xb9, 0xed, 0x5e, 0xe8, 0x25, 0xc7, 0xa4,
	0x78, 0x0e, 0xe7, 0x7b, 0xc1, 0xa9, 0x13, 0xec, 0xf1, 0xf4, 0x27, 0x5c, 0xb4, 0x9d, 0xc5, 0x08,
	0x82, 0x45, 0x6e, 0x0b, 0xf4, 0xb5, 0x30, 0x10, 0x02, 0xce, 0xbe, 0xa0, 0x32, 0xde, 0xde, 0x9d,
	0xc5, 0x18, 0xc2, 0x7c, 0x9b, 0xad, 0xe3, 0xc8, 0x7b, 0x7a, 0x44, 0xda, 0xc5, 0xe3, 0x0e, 0xe5,
	0x19, 0x6b, 0xe9, 0x4c, 0xda, 0xb9, 0xae, 0x2c, 0x1a, 0x19, 0xb0, 0x96, 0xd1, 0xf4, 0x1a, 0xe0,
	0x16, 0x6d, 0xd3, 0xcc, 0x21, 0x9c, 0xc4, 0x91, 0x7f, 0xf8, 0x24, 0x8e, 0xa6, 0xbf, 0x03, 0xe8,
	0xbb, 0xdf, 0xbe, 0x8e, 0x7f, 0xcf, 0x36, 0x82, 0x20, 0x51, 0x16, 0x33, 0x1f, 0x8d, 0x01, 0xf7,
	0xa1, 0x40, 0x55, 0x61, 0xe6, 0xd3, 0xed, 0xb1, 0x90, 0xd0, 0x4d, 0xea, 0xd2, 0xe6, 0x5b, 0xf4,
	0x11, 0x1b, 0x48, 0x5e, 0xb7, 0x58, 0x1a, 0x94, 0x21, 0x7b, 0x39, 0x40, 0x5e, 0x51, 0x6e, 0x30,
	0xb5, 0xda, 0xc8, 0x2e, 0x7b, 0x35, 0x98, 0xaa, 0x5d, 0x99, 0x9c, 0xaa, 0x3d, 0xe7, 0x6a, 0x19,
	0x11, 0xff, 0x9e, 0x04, 0x95, 0xec, 0x31, 0xcf, 0x88, 0x2a, 0x98, 0x17, 0xda, 0x4a, 0xe0, 0x0a,
	0xe8, 0x4c, 0xfe, 0x9f, 0x54, 0xb9, 0xa9, 0xd5, 0x06, 0x65, 0x9f, 0xfd, 0x1b, 0x4c, 0x59, 0x3f,
	0xea, 0xba, 0xb4, 0xe6, 0x51, 0x5e, 0x70, 0x56, 0x0f, 0xdd, 0x0b, 0xdf, 0x95, 0xc9, 0x2a, 0x39,
	0xf0, 0x2f, 0x38, 0xd4, 0xea, 0xff, 0xb0, 0xdd, 0x7f, 0xf1, 0x0a, 0xba, 0x89, 0xb2, 0x79, 0xb9,
	0xa9, 0xe4, 0x7f, 0x6e, 0xda, 0x06, 0x7e, 0xda, 0x98, 0x4d, 0x9a, 0xbf, 0xe2, 0x1a, 0x7a, 0x9f,
	0xd1, 0xaa, 0x2a, 0xd5, 0x06, 0xe5, 0xa5, 0xf3, 0x38, 0x10, 0x34, 0xe5, 0xf1, 0x36, 0x5b, 0xb3,
	0x58, 0xfe, 0xcf, 0x5b, 0x70, 0x60, 0xe8, 0x36, 0xa1, 0xa5, 0xb6, 0x58, 0x49, 0xc1, 0xb7, 0xf7,
	0x04, 0x85, 0x8b, 0x79, 0x90, 0xae, 0x38, 0x5c, 0x7c, 0x3c, 0x48, 0xa3, 0xd6, 0x20, 0x5d, 0xc2,
	0x69, 0xb4, 0x8c, 0xe4, 0x13, 0x47, 0xd1, 0x91, 0xbc, 0x3f, 0xe8, 0x1f, 0x77, 0x0f, 0x0f, 0x79,
	0x8a, 0x72, 0xcc, 0xde, 0x7b, 0xc2, 0xed, 0x9f, 0xd1, 0x59, 0x9d, 0xba, 0xfd, 0x7b, 0xca, 0xc9,
	0x0e, 0x0c, 0xb5, 0x72, 0x85, 0xeb, 0x2a, 0xb7, 0x28, 0x25, 0xb7, 0xd2, 0xc3, 0xa3, 0xa5, 0x79,
	0xf6, 0xd7, 0xd2, 0xbc, 0x83, 0xd0, 0x57, 0x36, 0x86, 0xf0, 0x5e, 0xd7, 0x26, 0x6d, 0x66, 0xd2,
	0x23, 0x1a, 0x9a, 0xa5, 0x2a, 0xea, 0x66, 0x21, 0x19, 0xac, 0x43, 0xd7, 0xdc, 0xb7, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0x86, 0x1a, 0xa7, 0x5a, 0x04, 0x00, 0x00,
}
