// Automatically generated by MockGen. DO NOT EDIT!
// Source: ../service/types.service.go

package usecase

import (
	entity "my-projects/stockbit/internal/entity"

	gomock "github.com/golang/mock/gomock"
)

// Mock of Movie interface
type MockMovie struct {
	ctrl     *gomock.Controller
	recorder *_MockMovieRecorder
}

// Recorder for MockMovie (not exported)
type _MockMovieRecorder struct {
	mock *MockMovie
}

func NewMockMovie(ctrl *gomock.Controller) *MockMovie {
	mock := &MockMovie{ctrl: ctrl}
	mock.recorder = &_MockMovieRecorder{mock}
	return mock
}

func (_m *MockMovie) EXPECT() *_MockMovieRecorder {
	return _m.recorder
}

func (_m *MockMovie) Search(request entity.SearchRequest) (entity.SearchResponse, error) {
	ret := _m.ctrl.Call(_m, "Search", request)
	ret0, _ := ret[0].(entity.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockMovieRecorder) Search(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Search", arg0)
}

func (_m *MockMovie) Get(request entity.GetRequest) (entity.GetResponse, error) {
	ret := _m.ctrl.Call(_m, "Get", request)
	ret0, _ := ret[0].(entity.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockMovieRecorder) Get(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0)
}
